// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://iytyyxlromryurixtalw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Iml5dHl5eGxyb21yeXVyaXh0YWx3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI4NTA0MzAsImV4cCI6MjA2ODQyNjQzMH0.22Sgp_ZgTRBMsOmdk5EQ_P_BwUjZY7oCcobuEOEylN8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});